# This overrides the config in the Dependabot UI.
# We're trialling this to see if it can be used as
# a way to reduce the number of Dependabot PRs for
# gems where updates aren't so valuable.
version: 1
update_configs:
  - package_manager: ruby:bundler
    directory: /
    update_schedule: daily
    allowed_updates:
      # Security updates - we should always do these
      - match: { update_type: security }
      - match: { dependency_name: brakeman }
      # Internal gems - we should always update these
      - match: { dependency_name: gds-api-adapters }
      - match: { dependency_name: gds-sso }
      - match: { dependency_name: govspeak }
      - match: { dependency_name: govuk_app_config }
      - match: { dependency_name: govuk_publishing_components }
      - match: { dependency_name: govuk_schemas }
      - match: { dependency_name: govuk_sidekiq }
      - match: { dependency_name: govuk_test }
      - match: { dependency_name: rubocop-govuk }
      - match: { dependency_name: plek }
      - match: { dependency_name: scss_lint-govuk }
      # Framework gems - we use these to write lots of code
      - match: { dependency_name: factory_bot_rails }
      - match: { dependency_name: jasmine }
      - match: { dependency_name: rails }
      - match: { dependency_name: rspec-rails }
      - match: { dependency_name: sass-rails }
      - match: { dependency_name: sassc-rails }
  - package_manager: javascript
    directory: /
    update_schedule: daily
    allowed_updates:
      # Security updates - we should always do these
      - match: { update_type: security }
      # Internal packages - we should always update these
      - match: { dependency_name: accessible-autocomplete }
      - match: { dependency_name: markdown-toolbar-element }
      - match: { dependency_name: miller-columns-element }
      - match: { dependency_name: paste-html-to-govspeak }
      # Framework packages - we use these to write lots of code
      - match: { dependency_name: govuk-frontend }
